### ISSUE TITLE
Cannot see GhidraAssistant analisys plugin

### ISSUE THREAD

**Issue by velteyn** [cyberkaida/reverse-engineering-assistant#28]
Hello,
I compiled Ghidra assistant for Ghidra 11

I checked the plugin when Ghidra starts. The log shows:
2024-02-02 | 10:40:02 | INFO | (GhidraAssistantPlugin) Ghidra Assistant plugin loading

I opened the analysis tool but I have 
2024-02-03 | 11:47:05 | WARN | (PluginPackage) Can't find plugin package for GhidraAssistant! Creating stub...

When I open the Ghidra analisys tool the plugin is not there...

What can I do  ?
Thank you

**Comment by cyberkaida** [comment]
Hi @velteyn ! Can you please attach your Ghidra application log after reproducing this issue? You will find it in `~.ghidra/.ghidra_11.0_PUBLIC/application.log`

Do you see the plugin in the configuration?

If you open the CodeBrowser tool by double clicking a file in the project view, then open `File -> Configure`.

<img width="685" alt="Screenshot 2024-02-05 at 07 52 28" src="https://github.com/cyberkaida/reverse-engineering-assistant/assets/118712366/5a212d5b-c7c1-444e-a5df-21248bd7109f">

You can click this icon on the top to list all plugins and search for `Reva` (it should also be in the Miscellaneous category)

<img width="703" alt="Screenshot 2024-02-05 at 07 54 52" src="https://github.com/cyberkaida/reverse-engineering-assistant/assets/118712366/3aca1cb6-5de2-4255-89fc-dabb1248be77">

**Comment by cyberkaida** [comment]
Please check the latest version of the README. It was really out of date, sorry.

**Comment by cyberkaida** [comment]
@velteyn did this solve your issue?

**Comment by velteyn** [comment]
Ah sorry, I haven't had time to look at it yet, hopefully by this weekend.

**Comment by velteyn** [comment]
![immagine](https://github.com/cyberkaida/reverse-engineering-assistant/assets/1019294/d863f4a2-b2ff-40f7-8945-09d4463d0ea1)
Cannot see the plugin .

**Comment by velteyn** [comment]
![immagine](https://github.com/cyberkaida/reverse-engineering-assistant/assets/1019294/1f2cf23d-b580-4bd5-951e-984170e817d0)

**Comment by velteyn** [comment]
[application.log](https://github.com/cyberkaida/reverse-engineering-assistant/files/14229806/application.log)
I attach the log.

**Comment by velteyn** [comment]
Ok I tried to rebuild it and configure, and now the plugin is on the list. I enabled it but I cannot see any difference on the analysis list...
![immagine](https://github.com/cyberkaida/reverse-engineering-assistant/assets/1019294/8da77f02-ddfe-4e4a-b4d6-d390f02b870b)

**Comment by cyberkaida** [comment]
The plugin does not (yet) add an analysis module. Please see [the readme](https://github.com/cyberkaida/reverse-engineering-assistant?tab=readme-ov-file#usage). You need to start the python side and once you do that you can ask questions.
