### ISSUE TITLE
First attempt to start ig gives error message

### ISSUE THREAD

**Issue by marcellmajor** [cyberkaida/reverse-engineering-assistant#34]
Traceback (most recent call last):
  File "/opt/conda/bin/revassistant", line 5, in <module>
    from reverse_engineering_assistant.assistant import main
  File "/opt/conda/lib/python3.10/site-packages/reverse_engineering_assistant/assistant.py", line 34, in <module>
    from .configuration import AssistantConfiguration, load_configuration
  File "/opt/conda/lib/python3.10/site-packages/reverse_engineering_assistant/configuration.py", line 7, in <module>
    from typing import Literal, TypedDict, Optional, NotRequired, Dict
ImportError: cannot import name 'NotRequired' from 'typing' (/opt/conda/lib/python3.10/typing.py)

**Comment by cyberkaida** [comment]
Sorry @marcellmajor ! I hope this wasn't too frustrating!

The error is coming from your `typing-extensions` package being out of date. I develop ReVa on Python3.12. My version of `typing-extensions` is:

```sh
% python3 -m pip list
 | grep -i typing
typing_extensions             4.10.0
```

This package should be install by pydantic (I think), please try upgrading your packages, then if that fails, upgrade your python version. I might also use some `match` syntax that was introduced in more recent python.

I will update the package and the requirements.txt to be more explicit.

Thank you! Please leave a comment if this works for you, and thank you for trying my software! I hope it serves you well!
