### ISSUE TITLE
Fix ghidra-assistant build on Windows

### ISSUE THREAD

**Issue by unkmc** [cyberkaida/reverse-engineering-assistant#43]
Gradle build on windows is currently failing with errors, e.g.
`Execution failed for task ':generateProto'. > Source directory 'D:\github\reverse-engineering-assistant-fork\ghidra-assistant\src\main\proto' is not a directory.`

and

`Reason: Task ':extractIncludeProto' uses this output of task ':copyDependencies' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.`

**Comment by cyberkaida** [comment]
Relating
#51

**Comment by unkmc** [comment]
Second PR: https://github.com/cyberkaida/reverse-engineering-assistant/pull/53
