### ISSUE TITLE
build error about gradle

### ISSUE THREAD

**Issue by madjohn698** [cyberkaida/reverse-engineering-assistant#64]
when I use gradle to build ghidra assistant, there are some error on below:
`test@vm:~/ai/re/ghidra-assistant$ gradle -PGHIDRA_INSTALL_DIR="/opt/ghidra"

FAILURE: Build failed with an exception.

* Where:
Build file '/home/test/ai/re/ghidra-assistant/build.gradle' line: 33

* What went wrong:
Plugin [id: 'com.google.protobuf', version: '0.9.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.google.protobuf:com.google.protobuf.gradle.plugin:0.9.4')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
`
my gradle version is 7.2, the detail is:
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Private Build 16.0.1+9-Ubuntu-120.04)
OS:           Linux 5.19.0-50-generic amd64

**Comment by cyberkaida** [comment]
I am not sure about this. I wonder if Gradle is able to pull from Maven Central. Do you have more information about your setup? I will try to recreate using a container.

**Comment by cyberkaida** [comment]
Please also update your Java install, I think it is below the required version for Ghidra and Protobuf. This might be the issue.

**Comment by madjohn698** [comment]
my java info is below：
test@vm:~$ java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-122.04, mixed mode, sharing)
maybe the gradle is not able to pull from Maven Central.
After make protocol, I want to do 'gradle -PGHIDRA_INSTALL_DIR="/opt/ghidra"', these is my step.
