### ISSUE TITLE
Are there detailed installation instructions?

### ISSUE THREAD

**Issue by madjohn698** [cyberkaida/reverse-engineering-assistant#65]
After I compile all the code, I still get an error when running reva-server. In addition, if I want to support Gemini, can I just add an openai-compatible baseurl to the ChatOpenAI function?Thanks.

**Comment by cyberkaida** [comment]
I will work on the installation instructions. I will also make a video.

To add Gemini support a change to the settings menu in the Ghidra plugin will be required and a change to the Reva-server will be required.

**Comment by cyberkaida** [comment]
If you have not, please try the pull request #63. I have updated the instructions in that pull request. I will make more improvements next week.
