### ISSUE TITLE
Another error after fresh install

### ISSUE THREAD

**Issue by velteyn** [cyberkaida/reverse-engineering-assistant#72]
Hi there , long time no see. How are U ?
I see the project is quite different from the early one. I tried to reinstall all.
First problem:
i run make protocol but i obtained the following after reva-server :

```
Traceback (most recent call last):
  File "/home/velteyn/.local/bin/reva-server", line 5, in <module>
    from reverse_engineering_assistant.assistant_api_server import main
  File "/home/velteyn/.local/share/pipx/venvs/reverse-engineering-assistant/lib/python3.12/site-packages/reverse_engineering_assistant/assistant_api_server.py", line 23, in <module>
    from .protocol import RevaHandshake_pb2_grpc, RevaHandshake_pb2
ModuleNotFoundError: No module named 'reverse_engineering_assistant.protocol'
```

so I tried to put the generated protocol folder to 
![immagine](https://github.com/user-attachments/assets/96e8e6e1-0bc6-4d3d-9fb3-6ddf14778885)
but now I obtain:
![immagine](https://github.com/user-attachments/assets/8291fcc6-0a5c-47fc-bf45-b56f2c6aa8d3)

**Comment by cyberkaida** [comment]
This looks like two issues:
- Protobufs failing to build
- Incompatible version of langgraph

**Comment by cyberkaida** [comment]
My current working virtual environment contains:

```
Package                       Version
----------------------------- ---------
aiohttp                       3.9.5
aiosignal                     1.3.1
annotated-types               0.7.0
anyio                         4.4.0
attrs                         23.2.0
blinker                       1.8.2
certifi                       2024.7.4
charset-normalizer            3.3.2
click                         8.1.7
dataclasses-json              0.6.7
diskcache                     5.6.3
distro                        1.9.0
filelock                      3.15.4
Flask                         3.0.3
frozenlist                    1.4.1
fsspec                        2024.6.1
grpcio                        1.64.1
h11                           0.14.0
httpcore                      1.0.5
httpx                         0.27.0
huggingface-hub               0.23.4
idna                          3.7
itsdangerous                  2.2.0
Jinja2                        3.1.4
joblib                        1.4.2
jsonpatch                     1.33
jsonpointer                   3.0.0
langchain                     0.2.6
langchain-community           0.2.6
langchain-core                0.2.11
langchain-experimental        0.0.62
langchain-openai              0.1.14
langchain-text-splitters      0.2.2
langgraph                     0.1.5
langsmith                     0.1.84
llama_cpp_python              0.2.64
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
marshmallow                   3.21.3
mdurl                         0.1.2
mpmath                        1.3.0
multidict                     6.0.5
mypy-extensions               1.0.0
networkx                      3.3
numpy                         1.26.4
openai                        1.35.10
orjson                        3.10.6
packaging                     24.1
pillow                        10.4.0
pip                           24.1.1
prompt_toolkit                3.0.47
protobuf                      5.27.2
pydantic                      2.8.2
pydantic_core                 2.20.1
Pygments                      2.18.0
PyYAML                        6.0.1
regex                         2024.5.15
requests                      2.32.3
reverse-engineering-assistant 2.9.3
rich                          13.7.1
safetensors                   0.4.3
scikit-learn                  1.5.1
sentence-transformers         3.0.1
sniffio                       1.3.1
SQLAlchemy                    2.0.31
sympy                         1.12.1
tenacity                      8.5.0
threadpoolctl                 3.5.0
tiktoken                      0.7.0
tokenizers                    0.19.1
torch                         2.3.1
tqdm                          4.66.4
typing_extensions             4.12.2
typing-inspect                0.9.0
urllib3                       2.2.2
wcwidth                       0.2.13
Werkzeug                      3.0.3
yarl                          1.9.4
```

**Comment by cyberkaida** [comment]
Please let me know what version of langgraph was installed on your system.

You can get the content of the pipx virtual environment with this command:

`pipx runpip reverse-engineering-assistant list`

**Comment by cyberkaida** [comment]
Can you try installing from the pip release? I want to check your build system for protobuf.

**Comment by velteyn** [comment]
Excuse for the late response
here it is the pipix response

(venv) [velteyn@ultrapiuter projects]$ pipx runpip reverse-engineering-assistant list
Package                       Version
----------------------------- ----------
aiohttp                       3.9.5
aiosignal                     1.3.1
annotated-types               0.7.0
anyio                         4.4.0
attrs                         23.2.0
blinker                       1.8.2
certifi                       2024.7.4
charset-normalizer            3.3.2
click                         8.1.7
dataclasses-json              0.6.7
distro                        1.9.0
filelock                      3.15.4
Flask                         3.0.3
frozenlist                    1.4.1
fsspec                        2024.6.1
greenlet                      3.0.3
grpcio                        1.65.1
h11                           0.14.0
httpcore                      1.0.5
httpx                         0.27.0
huggingface-hub               0.24.0
idna                          3.7
itsdangerous                  2.2.0
Jinja2                        3.1.4
joblib                        1.4.2
jsonpatch                     1.33
jsonpointer                   3.0.0
langchain                     0.2.10
langchain-community           0.2.9
langchain-core                0.2.22
langchain-experimental        0.0.62
langchain-openai              0.1.17
langchain-text-splitters      0.2.2
langgraph                     0.1.9
langsmith                     0.1.93
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
marshmallow                   3.21.3
mdurl                         0.1.2
mpmath                        1.3.0
multidict                     6.0.5
mypy-extensions               1.0.0
networkx                      3.3
numpy                         1.26.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.20.5
nvidia-nvjitlink-cu12         12.5.82
nvidia-nvtx-cu12              12.1.105
openai                        1.36.0
orjson                        3.10.6
packaging                     24.1
pillow                        10.4.0
pip                           24.1.2
prompt_toolkit                3.0.47
protobuf                      5.27.2
pydantic                      2.8.2
pydantic_core                 2.20.1
Pygments                      2.18.0
PyYAML                        6.0.1
regex                         2024.5.15
requests                      2.32.3
reverse-engineering-assistant 2.9.4
rich                          13.7.1
safetensors                   0.4.3
scikit-learn                  1.5.1
scipy                         1.14.0
sentence-transformers         3.0.1
sniffio                       1.3.1
SQLAlchemy                    2.0.31
sympy                         1.13.1
tenacity                      8.5.0
threadpoolctl                 3.5.0
tiktoken                      0.7.0
tokenizers                    0.19.1
torch                         2.3.1
tqdm                          4.66.4
transformers                  4.42.4
typing_extensions             4.12.2
typing-inspect                0.9.0
urllib3                       2.2.2
wcwidth                       0.2.13
Werkzeug                      3.0.3
yarl                          1.9.4

**Comment by velteyn** [comment]
Now I reinstalled again and I have this :(
![immagine](https://github.com/user-attachments/assets/a943530e-272c-4afb-97db-ca749615308f)

**Comment by kofa2002** [comment]
> Now I reinstalled again and I have this :( ![immagine](https://private-user-images.githubusercontent.com/1019294/358552905-a943530e-272c-4afb-97db-ca749615308f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzUyODUsIm5iZiI6MTcyODA3NDk4NSwicGF0aCI6Ii8xMDE5Mjk0LzM1ODU1MjkwNS1hOTQzNTMwZS0yNzJjLTRhZmItOTdkYi1jYTc0OTYxNTMwOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMjA0OTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmJmNTI5MWNkNDdhMTM1MTE3ZWNiNTIwOGMxYjU1ODNkYzYzMWRlNjA0ZmU2ZTZiNmFlNjM1NTM3NDNmMTU5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._2uEg6lqfqyff0M2irabBRYXOVJ7kDKT5dNUu0ZtKy8)

i had the same problem before ,  install langgraph-checkpoint-sqlite separatly or add it to the requirement.txt file and rebuild the reva-server , its should work

**Comment by velteyn** [comment]
Ok I give up ! I pass most of the time to attempt to let it work but I'm not able.. Maybe one day when I'll be much proficient in Python I'll give it a try . My arch linux want it to work with a VENV but , dunno , the GHidra plugin is not there also if I built it correctly and I installed ,and when I attempt to let it start it continues to give me that damn langgraph-checkpoint-sqlite error also if I installed it everywhere also in my trousers. Dunno... Good Bye....
